//
// Created by mctrivia on 31/03/24.
//
// ============================================================
// WARNING: THIS FILE HAS AN UPSTREAM TEST DEPENDENCY
// ============================================================
// See RPCMethods.cpp for full details.
// All tests in RPCMethodsTest require testFiles/rpcTest.db,
// generated by DigiAssetTransaction.existingAssetTransactions.
//
// The SetUp() override in this header intentionally FAILS every
// test when rpcTest.db is absent.  Do NOT change it to skip.
// ============================================================
#ifndef RPC_METHODS_TEST_H
#define RPC_METHODS_TEST_H

#include "gtest/gtest.h"
#include "AppMain.h"

class RPCMethodsTest : public ::testing::Test {
protected:
    static void SetUpTestSuite();
    static void TearDownTestSuite();

    void SetUp() override {
        if (db == nullptr) {
            FAIL() << "rpcTest.db not found — run DigiAssetTransaction.existingAssetTransactions first (requires IPFS)";
        }
    }

    static AppMain* appMain;
    static DigiByteCore* dgb;
    static Database* db;
    static IPFS* ipfs;
    static PermanentStoragePoolList* psp;
    static ChainAnalyzer* analyzer;
    static RPC::Cache* rpcCache;
};

#endif // RPC_METHODS_TEST_H
