//
// Created by mctrivia on 31/03/24.
//
// ============================================================
// WARNING: THIS FILE HAS AN UPSTREAM TEST DEPENDENCY
// ============================================================
// See RPCMethods.cpp for full details.
// All tests in RPCMethodsTest require testFiles/rpcTest.db (generated by
// DigiAssetTransaction.existingAssetTransactions) AND a reachable DigiByte
// Core + IPFS.  When those are present the tests run normally; when they are
// NOT (e.g. a bare CI runner with no node), SetUp() SKIPS each test rather
// than failing, so the suite stays green instead of reporting false failures.
// ============================================================
#ifndef RPC_METHODS_TEST_H
#define RPC_METHODS_TEST_H

#include "gtest/gtest.h"
#include "AppMain.h"

class RPCMethodsTest : public ::testing::Test {
protected:
    static void SetUpTestSuite();
    static void TearDownTestSuite();

    void SetUp() override {
        if (db == nullptr) {
            GTEST_SKIP() << "requires testFiles/rpcTest.db + a reachable DigiByte Core/IPFS "
                            "(generate via DigiAssetTransaction.existingAssetTransactions). "
                            "Skipped so CI stays green when those services aren't available.";
        }
    }

    static AppMain* appMain;
    static DigiByteCore* dgb;
    static Database* db;
    static IPFS* ipfs;
    static PermanentStoragePoolList* psp;
    static ChainAnalyzer* analyzer;
    static RPC::Cache* rpcCache;
};

#endif // RPC_METHODS_TEST_H
